### ISSUE TITLE
Extending API Level support (currently from SDK 26)

### ISSUE THREAD

**Issue by jeluchu** [darkryh/Cloudflare-Bypass#1]
Hi, I've been looking at your project, and I don't know if you wanted to, but you can expand the device compatibility of your project. Currently you have the minimum SDK at 26, that limits many devices.

I've been testing, because I can use this and I made a subversion with a fork. The change to increase compatibility in case you want it, and be compatible from SDK 21, is as simple as changing the name of one of the folders you have of the mipmap, I leave it here in images.

**Current (minSdk 26)**
<img width="1032" alt="Captura de pantalla 2024-09-23 a las 23 11 37" src="https://github.com/user-attachments/assets/cf5af669-ae09-4bea-921e-7438fd58c2e3">
<img width="1032" alt="Captura de pantalla 2024-09-23 a las 23 11 22" src="https://github.com/user-attachments/assets/b2a099e4-7884-4e02-bcc8-b0960a4dcd1a">

**After renaming the folder mipmap-anydpi (minSdk 21)**
<img width="1032" alt="Captura de pantalla 2024-09-23 a las 23 11 43" src="https://github.com/user-attachments/assets/dd9c76e7-e651-4d5d-8bad-9bac5951d759">
<img width="1032" alt="Captura de pantalla 2024-09-23 a las 23 11 45" src="https://github.com/user-attachments/assets/376e3377-8229-4e84-af3a-1bb376b24691">

I hope it will help you in case you want to extend the compatibility of your library. Good luck!

**Comment by darkryh** [comment]
Thanks for the advice for sure I will change it, many of my apps are starting with 26 api, that I forgot to change it

**Comment by darkryh** [comment]
That  process has been applied
